### ISSUE TITLE
Demo site is broken throwing Uncaught DOMException: Blocked a frame with origin

### ISSUE THREAD

**Issue by gmkumar2005** [bem-site/bem.info#247]
When i access the links https://en.bem.info/platform/libs/bem-core/4.2.0/desktop/clearfix/
The chrome console is shown the below error

platform.en.min.js:3 Uncaught DOMException: Blocked a frame with origin "https://en.bem.info" from accessing a cross-origin frame.
    at h.updateIframeHeight (https://en.bem.info/platform.en.min.js:3:5692)
    at h.inited [as __after__mod_js_inited] (https://en.bem.info/platform.en.min.js:3:5556)
    at h._callModFn (https://en.bem.info/platform.en.min.js:1:23680)
    at h.setMod (https://en.bem.info/platform.en.min.js:1:22874)
    at h.setMod (https://en.bem.info/platform.en.min.js:1:9437)
    at h.setMod (https://en.bem.info/platform.en.min.js:1:26727)
    at h._init (https://en.bem.info/platform.en.min.js:1:21003)
    at Function._runInitFns (https://en.bem.info/platform.en.min.js:1:25629)
    at Function.init (https://en.bem.info/platform.en.min.js:1:12314)
    at Array.<anonymous> (https://en.bem.info/platform.en.min.js:1:19686)

Not sure if this is breaking any functionality, but work looking into this

**Comment by tadatuta** [comment]
We need to switch on CORS on static.bem.info for `*.bem.info` to fix the issue.

// cc @a-lexxx
